### ISSUE TITLE
[Bug] Old format string migrated from 1.x causes crash.

### ISSUE THREAD

**Issue by ryantheleach** [Draycia/Chat#179]
## Bug Description:

When using 
```
"<hover:show_text:'%luckperms_meta_namecolor%%player_displayname%\n%luckperms_meta_donator-explain%\n%luckperms_meta_explain%'>%luckperms_meta_donatorcolor%%luckperms_meta_donator%%luckperms_meta_rankcolor%%luckperms_meta_rank%%luckperms_meta_namecolor%%player_displayname%</hover><reset><gray> <reset> <message>"
```
 as my chat formatting string, a crash results in Carbon whenever a message is sent. 
 
 TLDR? This line: https://github.com/Hexaoxide/Carbon/blob/26ee2c320bdd98960a898e170b8a3432b0aa6878/bukkit/src/main/java/net/draycia/carbon/bukkit/util/PlaceholderAPIMiniMessageParser.java#L108

```
[19:05:56 WARN]: at carbonchat-bukkit-2.0.3.jar//net.draycia.carbon.bukkit.util.PlaceholderAPIMiniMessageParser.parse(PlaceholderAPIMiniMessageParser.java:108)
[19:05:56 WARN]: java.lang.IllegalArgumentException: Illegal group reference
[19:05:56 WARN]: at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1067)
[19:05:56 WARN]: at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)
[19:05:56 WARN]: at carbonchat-bukkit-2.0.3.jar//net.draycia.carbon.bukkit.util.PlaceholderAPIMiniMessageParser.parseRelational(PlaceholderAPIMiniMessageParser.java:80)
[19:05:56 WARN]: at carbonchat-bukkit-2.0.3.jar//net.draycia.carbon.bukkit.util.BukkitMessageRenderer.render(BukkitMessageRenderer.java:94)
[19:05:56 WARN]: at carbonchat-bukkit-2.0.3.jar//net.draycia.carbon.bukkit.util.BukkitMessageRenderer.render(BukkitMessageRenderer.java:48)
[19:05:56 WARN]: at carbonchat-bukkit-2.0.3.jar//net.draycia.carbon.libs.net.kyori.moonshine.MoonshineInvocationHandler.invoke(MoonshineInvocationHandler.java:98)
[19:05:56 WARN]: at carbonchat-bukkit-2.0.3.jar/jdk.proxy3/jdk.proxy3.$Proxy63.chatFormat(Unknown Source)
[19:05:56 WARN]: at carbonchat-bukkit-2.0.3.jar//net.draycia.carbon.common.channels.ConfigChatChannel.render(ConfigChatChannel.java:126)
[19:05:56 WARN]: at carbonchat-bukkit-2.0.3.jar//net.draycia.carbon.api.util.KeyedRenderer$Impl.render(KeyedRenderer.java:65)
[19:05:56 WARN]: at carbonchat-bukkit-2.0.3.jar//net.draycia.carbon.bukkit.listeners.BukkitChatListener.onPlayerChat(BukkitChatListener.java:117)
[19:05:56 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor32.execute(Unknown Source)
[19:05:56 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[19:05:56 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[19:05:56 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:05:56 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[19:05:56 WARN]: at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230)
[19:05:56 WARN]: at io.papermc.paper.adventure.ChatProcessor.processModern(ChatProcessor.java:138)
[19:05:56 WARN]: at io.papermc.paper.adventure.ChatProcessor.lambda$process$3(ChatProcessor.java:85)
[19:05:56 WARN]: at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:131)
[19:05:56 WARN]: at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64)
[19:05:56 WARN]: at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2185)
[19:05:56 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2096)
[19:05:56 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2062)
[19:05:56 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat$1.run(PacketPlayInChat.java:40)
[19:05:56 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[19:05:56 WARN]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[19:05:56 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[19:05:56 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:05:56 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
```

### Steps to reproduce:

1. Install Carbon, LuckPerms, PAPI, PAPI LP extension, PAPI Player extension
2. configure a channel called 'global' which formats the message using  `"<hover:show_text:'%luckperms_meta_namecolor%%player_displayname%\n%luckperms_meta_donator-explain%\n%luckperms_meta_explain%'>%luckperms_meta_donatorcolor%%luckperms_meta_donator%%luckperms_meta_rankcolor%%luckperms_meta_rank%%luckperms_meta_namecolor%%player_displayname%</hover><reset><gray> <reset> <message>"`
3. Have luckperms permissions defined like so: https://luckperms.net/editor/NjSrMfjxT6 (copy ryan_the_leach to your profile to reproduce the crash) (you can use this to import `/luckperms import 9Mypm7oCJX --upload`
4. Send a chat message to global, note that text is unformatted, and an error is thrown in the console.

### System Details:

```
This server is running Paper version git-Paper-77 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5ad1d9a)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
```
**Carbon Version**: 2.0.3

**Comment by Draycia** [comment]
ecb55e0
