### ISSUE TITLE
[Bug] Unsupported Database: PostgreSQL 16.1

### ISSUE THREAD

**Issue by SantaSpeen** [Draycia/Chat#377]
### System Details:

1. Server Type:           Paper
2. Server Software:    364
3. MC Version:          1,20,4
4. Carbon Version:    beta25

### Pastebins:

```
[18:12:35] [Server thread/ERROR]: [CarbonChat] Error initializing plugin 'carbonchat-paper-3.0.0-beta.25.jar' in folder 'plugins' (Is it up to date?)
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: FlywayException: Unsupported Database: PostgreSQL 16.1
  at CarbonCommonModule.userManager(CarbonCommonModule.java:132)
      \_ installed by: CarbonChatPaperModule -> CarbonCommonModule
  at PlatformUserManager.<init>(PlatformUserManager.java:37)
      \_ for 1st parameter backingManager
  at PlatformUserManager.class(PlatformUserManager.java:37)
  while locating PlatformUserManager
  at CarbonServerPaper.<init>(CarbonServerPaper.java:50)
      \_ for 2nd parameter userManager
  at CarbonServerPaper.class(CarbonServerPaper.java:50)
  while locating CarbonServerPaper
  at CarbonChatPaper.<init>(CarbonChatPaper.java:98)
      \_ for 7th parameter carbonServer
  at CarbonChatPaper.class(CarbonChatPaper.java:98)
  while locating CarbonChatPaper

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
CarbonChatPaper:       "net.draycia.carbon.paper.CarbonChatPaper"
CarbonChatPaperModule: "net.draycia.carbon.paper.CarbonChatPaperModule"
CarbonCommonModule:    "net.draycia.carbon.common.CarbonCommonModule"
CarbonServerPaper:     "net.draycia.carbon.paper.CarbonServerPaper"
FlywayException:       "org.flywaydb.core.api.FlywayException"
PlatformUserManager:   "net.draycia.carbon.common.users.PlatformUserManager"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[?:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1104) ~[?:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1139) ~[?:?]
	at net.draycia.carbon.paper.CarbonPaperBootstrap.onLoad(CarbonPaperBootstrap.java:37) ~[carbonchat-paper-3.0.0-beta.25.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.4.jar:git-Paper-364]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.4.jar:git-Paper-364]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.4.jar:git-Paper-364]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-364]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505) ~[paper-1.20.4.jar:git-Paper-364]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.4.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-364]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 16.1
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:105) ~[?:?]
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1089) ~[?:?]
...
```

### Any other relevant details:

confgi:
```conf
# The service that will be used to store and load player information.
# One of: JSON, H2, MYSQL, PSQL
# Note: If you choose MYSQL or PSQL make sure you configure the "database-settings" section of this file!
storage-type=PSQL
# When "storage-type" is set to MYSQL or PSQL, this section configures the database connection.
# If JSON or H2 storage is used, this section can be ignored.
database-settings {
    # JDBC URL. Suggested defaults for each DB:
    # MySQL: jdbc:mysql://host:3306/DB
    # MariaDB: jdbc:mariadb://host:3306/DB
    # PostgreSQL: jdbc:postgresql://host:5432/database
    url="jdbc:postgresql://main.local:15002/carbon"
    # The connection username.
    username=user
    # The connection password.
    password="12345678"
    # Settings for the connection pool. This is an advanced configuration that most users won't need to touch.
    connection-pool {
        maximum-pool-size=8
        minimum-idle=8
        maximum-lifetime=1800000
        keepalive-time=0
        connection-timeout=30000
    }
}
```

db:
```yml
  # Main DB
  omins-postgres:
    hostname: omnis-postgres
    container_name: omins-postgres
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=minecraftDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "15002:5432"
    networks:
      - omins
```

**Comment by SantaSpeen** [comment]
What version i need?

**Comment by SantaSpeen** [comment]
LuckPerms and AuthMe works perfectly with pgsql 16.1

**Comment by SantaSpeen** [comment]
(database carbon added via psql)

**Comment by jpenilla** [comment]
Please try with the latest dev build: https://nightly.link/Hexaoxide/Carbon/workflows/build/trunk/Jars.zip

**Comment by SantaSpeen** [comment]
Same problem: [latest.log](https://github.com/Hexaoxide/Carbon/files/13804652/latest.log)

**Comment by jpenilla** [comment]
https://github.com/Hexaoxide/Carbon/commit/3e871511646c7c6491da6df18f0b4208982fa3ac this should fix it, flyway moved postgres support to a separate artifact recently

**Comment by SantaSpeen** [comment]
can u build artifact for me?

**Comment by jpenilla** [comment]
The same link from before will contain that commit now

**Comment by SantaSpeen** [comment]
i think u ar genius

```
[23:15:46] [Server thread/INFO]: [CarbonChat] Loading server plugin CarbonChat v3.0.0-SNAPSHOT+3e87151
[23:15:47] [Server thread/INFO]: [CarbonChat] Loading configuration....
[23:15:47] [Server thread/INFO]: [CarbonChat] Loaded 5 locales: [ja_JP, tr_TR, nl_NL, ru_RU, en_US]
[23:15:47] [Server thread/INFO]: [CarbonChat] Initializing PSQL storage manager...
[23:15:47] [Server thread/INFO]: [carbonchat.libs.com.zaxxer.hikari.HikariDataSource] CarbonChat-HikariPool - Starting...
[23:15:48] [Server thread/INFO]: [carbonchat.libs.com.zaxxer.hikari.pool.HikariPool] CarbonChat-HikariPool - Added connection org.postgresql.jdbc.PgConnection@48b04f6c
[23:15:48] [Server thread/INFO]: [carbonchat.libs.com.zaxxer.hikari.HikariDataSource] CarbonChat-HikariPool - Start completed.
[23:15:48] [Server thread/INFO]: [CarbonChat] Executing Flyway database migrations...
[23:15:48] [Server thread/INFO]: [CarbonChat]   [ClassPathScanner] Flyway OSS Edition 10.4.1 by Redgate
[23:15:48] [Server thread/INFO]: [CarbonChat]   [ClassPathScanner] 
[23:15:48] [Server thread/INFO]: [CarbonChat]   [ClassPathScanner] See release notes here: https://rd.gt/416ObMi
[23:15:48] [Server thread/INFO]: [CarbonChat]   [FlywayExecutor] Database: jdbc:postgresql://localhost:15002/carbon (PostgreSQL 16.1)
[23:15:48] [Server thread/INFO]: [CarbonChat]   [JdbcTableSchemaHistory] Repair of failed migration in Schema History table "public"."flyway_schema_history" not necessary as table doesn't exist.
[23:15:48] [Server thread/INFO]: [CarbonChat]   [JdbcTableSchemaHistory] Schema history table "public"."flyway_schema_history" does not exist yet
[23:15:48] [Server thread/INFO]: [CarbonChat]   [DbRepair] Successfully repaired schema history table "public"."flyway_schema_history" (execution time 00:00.031s).
[23:15:48] [Server thread/INFO]: [CarbonChat]   [JdbcTableSchemaHistory] Schema history table "public"."flyway_schema_history" does not exist yet
[23:15:48] [Server thread/INFO]: [CarbonChat]   [DbValidate] Successfully validated 7 migrations (execution time 00:00.005s)
[23:15:48] [Server thread/INFO]: [CarbonChat]   [JdbcTableSchemaHistory] Creating Schema History table "public"."flyway_schema_history" ...
[23:15:48] [Server thread/INFO]: [CarbonChat]   [DbMigrate] Current version of schema "public": << Empty Schema >>
[23:15:48] [Server thread/INFO]: [CarbonChat]   [DbMigrate] Migrating schema "public" to version "1 - create tables"
[23:15:49] [Server thread/INFO]: [CarbonChat]   [DbMigrate] Migrating schema "public" to version "2 - create tables"
[23:15:49] [Server thread/INFO]: [CarbonChat]   [DbMigrate] Migrating schema "public" to version "3 - fix leftchannels"
[23:15:49] [Server thread/INFO]: [CarbonChat]   [DbMigrate] Migrating schema "public" to version "4 - drop usernames"
[23:15:49] [Server thread/INFO]: [CarbonChat]   [DbMigrate] Migrating schema "public" to version "5 - add dmtoggle"
[23:15:49] [Server thread/INFO]: [CarbonChat]   [DbMigrate] Migrating schema "public" to version "6 - increase nickname size"
[23:15:49] [Server thread/INFO]: [CarbonChat]   [DbMigrate] Migrating schema "public" to version "7 - parties"
[23:15:49] [Server thread/INFO]: [CarbonChat]   [DbMigrate] Successfully applied 7 migrations to schema "public", now at version v7 (execution time 00:00.504s)
```

**Comment by SantaSpeen** [comment]
works perfectly

**Comment by SantaSpeen** [comment]
![image](https://github.com/Hexaoxide/Carbon/assets/68832064/726ada56-fe31-4487-b9af-368c7f6cd2d5)
New bugs
papi not works 
reload message

**Comment by SantaSpeen** [comment]
is radius works for velocity?
im set `radius=10`
but chat like global

**Comment by Draycia** [comment]
Velocity doesn't track player locations. The only valid options for radius there are 0 (players must be on the same server) and -1 (global chat)
