### ISSUE TITLE
Fix null pointer exception

### ISSUE THREAD

**Issue by BurkenDev** [Draycia/Chat#457]
Fix null pointer exception:

[12:47:57 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "carbonchat.libs.cloud.commandframework.CommandTree$Node.getValue()" because the return value of "carbonchat.libs.cloud.commandframework.bukkit.BukkitCommand.namedNode()" is null
        at carbonchat.libs.cloud.commandframework.bukkit.BukkitCommand.getUsage(BukkitCommand.java:200) ~[carbonchat-paper-3.0.0-beta.26.jar:?]
        at org.bukkit.help.GenericCommandHelpTopic.<init>(GenericCommandHelpTopic.java:50) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.help.SimpleHelpMap.initializeCommands(SimpleHelpMap.java:136) ~[paper-1.20.4.jar:git-Paper-466]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[paper-1.20.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-466]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-466]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by jpenilla** [comment]
We can't discern anything from log snippets. You need to send the entire log (https://mclo.gs). This type of error is usually caused by another error further up the log, often invalid configs.
